AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AvailabilityZones: 
        - ap-south-1a
        - ap-south-1b
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "1"
      Tags:
        - Key: "Name"
          Value: "my-asg"
          PropagateAtLaunch: "true"
  
  MyLaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: "ami-01a4f99c4ac11b03c"
      InstanceType: "t2.micro"
      KeyName: "Test"
      SecurityGroups:
        - !Ref MySecurityGroup
  
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "My security group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
