Resources:
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "my-table"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ElastiCacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: "Subnet group for ElastiCache"
      SubnetIds:
        - "subnet-049bad67f4a6975e4"
        - "subnet-0da85b6456a8f11e9"

  ElastiCacheCluster:
    Type: "AWS::ElastiCache::CacheCluster"
    Properties:
      CacheNodeType: "cache.t2.micro"
      Engine: "redis"
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      VpcSecurityGroupIds:
        - "sg-0e1f5b1da7fcb7a49"

Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDBTable
  ElastiCacheClusterEndpoint:
    Value: !GetAtt ElastiCacheCluster.RedisEndpoint.Address
