Resources:
  DynamoDBGlobalTable:
    Type: "AWS::DynamoDB::GlobalTable"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"
      Replicas:
        - Region: "us-west-2"
        - Region: "eu-west-1"
