AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEFS:
    Type: "AWS::EFS::FileSystem"
    Properties:
      Encrypted: true
      PerformanceMode: "generalPurpose"
      ThroughputMode: "bursting"
      FileSystemTags:
        - Key: "Name"
          Value: "MyEFS"
  MyEFSMountTarget:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref MyEFS
      SubnetId: "subnet-049bad67f4a6975e4"
      SecurityGroups:
        - "sg-0e1f5b1da7fcb7a49"
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01a4f99c4ac11b03c"
      InstanceType: "t2.micro"
      KeyName: "Test"
      SubnetId: "subnet-049bad67f4a6975e4"
      SecurityGroupIds:
        - "sg-0e1f5b1da7fcb7a49"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y amazon-efs-utils
          mkdir /mnt/efs
          mount -t efs ${MyEFS}:/ /mnt/efs