AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEFS:
    Type: "AWS::EFS::FileSystem"
    Properties:
      Encrypted: true
      PerformanceMode: "generalPurpose"
      ThroughputMode: "bursting"
      FileSystemTags:
        - Key: "Name"
          Value: "MyEFS"
  MyEFSMountTarget:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref MyEFS
      SubnetId: "subnet-049bad67f4a6975e4"
      SecurityGroups:
        - "sg-0e1f5b1da7fcb7a49"
