AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SsmRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "ssm-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "ssm-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:DescribeInstanceInformation"
                  - "ssm:ListCommands"
                  - "ssm:ListCommandInvocations"
                  - "ssm:SendCommand"
                Resource: "*"
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref "SsmRole"
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01a4f99c4ac11b03c"
      InstanceType: "t2.micro"
      KeyName: "Test"
      IamInstanceProfile: !Ref "InstanceProfile"
