AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2S3RDSPermissionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: EC2S3RDSPermissions
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource: "arn:aws:s3:::*"
          - Effect: Allow
            Action:
            - ec2:*
            Resource: "*"
          - Effect: Allow
            Action:
            - rds:*
            Resource: "*"
