Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: my-db-instance
      Engine: mysql
      EngineVersion: "8.0.25"
      MasterUsername: admin
      MasterUserPassword: password
      MultiAZ: true