Resources:
  MyDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: "my-rds-instance"
      Engine: "mysql"
      DBName: "mydatabase"
      MasterUsername: "myuser"
      MasterUserPassword: "mypassword"
      DBInstanceClass: "db.t2.micro"
      AllocatedStorage: "10"
      BackupRetentionPeriod: "7"
      VPCSecurityGroups:
        - "sg-0754dddfc44a09fe4" # Replace with your security group ID
      DBSubnetGroupName: "MyDBSubnetGroup"
      MultiAZ: "false"

Resources:
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: my-dbsubnet-group
      DBSubnetGroupDescription: "My DB subnet group"
      SubnetIds:
        - subnet-049bad67f4a6975e4 # Replace with the ID of the subnet in your VPC
        - subnet-0da85b6456a8f11e9 # Replace with the ID of another subnet in your VPC
