AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket for a static website

Resources:
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid": PublicReadGetObject
            Action: s3:GetObject
            Effect: Allow
            Resource: arn:aws:s3:::exampleanagh-bucket-name/*
            Principal: '*'

Outputs:
  WebsiteURL:
    Value: !Sub 'http://${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Description: URL of the static website
